local
a={a='config',b='GAC_IntegCheck',c='INTEGRITY_CHECKS_INTERVAL',d='Network'}local
b=IsValid
local
c=hook.Add
local
d=isbool
local
e=isnumber
local
f=pairs
local
g=CurTime
local
h=player.GetHumans
local
i=timer.Simple
local
j=util.TableToJSON
if!gAC[a.a].INTEGRITY_CHECKS
then
return
end
local
k={}for
l,m
in
f(gAC[a.a])do
if
gAC[a.a].INTEGRITY_INGORES[l]then
continue
end
if
d(m)or
e(m)then
k[l]=m
end
end
k=j(k)c("gAC.CLFilesLoaded","g-AC_verify_initialspawn",function(l)l[a.b]=g()+gAC[a.a][a.c]end)c("Think","g-AC_IntergrityCheck",function()local
l=h()local
m=g()for
n=1,#l
do
local
o=l[n]if
o[a.b]and
o[a.b]<m
then
gAC[a.d]:Send("g-AC_ACVerify",k,o)o[a.b]=m+gAC[a.a][a.c]end
end
end)gAC[a.d]:AddReceiver("g-AC_ACVerify",function(l,m)gAC.AddDetection(m,"Integrity check failure [Code 117]",gAC[a.a].INTEGRITY_CHECKS_PUNISHMENT,gAC[a.a].INTEGRITY_CHECKS_BANTIME)end)