local
b=Color
local
c=IsValid
local
d=MsgC
local
e=net.Start
local
f=net.WriteTable
local
g=pairs
local
h=player.GetAll
local
i=print
local
j=(SERVER
and
PrintMessage
or
NULL)local
k=(SERVER
and
net.Broadcast
or
NULL)local
l=(SERVER
and
net.Send
or
NULL)local
m=(SERVER
and
util.AddNetworkString
or
NULL)m("g-ACReceiveClientMessage1")m("g-ACReceiveClientMessage2")function
gAC.AdminMessage(n,o,p,q)for
r,s
in
g(h())do
if(gAC.PlayerHasAdminMessagePerm(s))then
e("g-ACReceiveClientMessage1")f({n,o,p,q})l(s)end
end
end
function
gAC.ClientMessage(n,o,p)if!c(n)then
d(b(30,150,255),gAC.config.SYNTAX,p,o.."\n")else
e("g-ACReceiveClientMessage2")f({o,p})l(n)end
end
function
gAC.PrintMessage(n,o,p)if
c(n)then
n:PrintMessage(o,p)else
i(p)end
end
function
gAC.Broadcast(n,o)e("g-ACReceiveClientMessage2")f({n,o})k()end