local a = {a='p',b='y',c='r',d='JoinTimeGAC',e='Meth_Silent_Last',f='Meth_Silent_Threshold',g='gAC_AimbotDetected',h='config',i='Meth_Silent_MX_Last',j='Meth_Silent_MY_Last'}if!gAC[a.h].ANTI_METH
then
return
end
local
b=CurTime
local
c=IsValid
local
d=hook.Add
local
e=math.abs
local
f={["weapon_physgun"]=true,["gmod_tool"]=true,["weapon_physcannon"]=true,["gmod_camera"]=true}local
function
g(j)return
j-(j%1)end
local
function
h(j,k)local
l=10^(k
or
0)return
g(j*l+.5)/l
end
local
function
i(j,k)j[a.a]=h(j[a.a],k)j[a.b]=h(j[a.b],k)j[a.c]=h(j[a.c],k)return
j
end
d("StartCommand","gAC.MethSilent",function(j,k)if(j:InVehicle()||j[a.g]||!j:Alive()||j:GetObserverMode()!=OBS_MODE_NONE||j:IsBot()||!c(j)||j:IsTimingOut()||j:PacketLoss()>80)then
return
end
if(j[a.d]==nil||!(b()>=j[a.d]+25)||j.PlayerFullyAuthenticated!=true)then
return
end
if
c(j:GetActiveWeapon())&&f[j:GetActiveWeapon():GetClass()]then
return
end
local
l=k:GetViewAngles()local
m,n,o=l[a.a],l[a.b],l[a.c]local
p=e(k:GetMouseX())local
q=e(k:GetMouseY())if!j[a.e]then
j[a.e]=l
j[a.i]=p
j[a.j]=q
j[a.f]=0
return
end
local
r,s=i(j[a.e]),i(l)if
p>0
and
q>0
and
r==s
then
if
j[a.f]>5
then
j[a.g]=true
gAC.AddDetection(j,"Meth Silent-Aim Detected [Code 115]",gAC[a.h].METH_PUNISHMENT,gAC[a.h].METH_BANTIME)return
else
j[a.f]=j[a.f]+1
end
elseif
j[a.f]>0
then
j[a.f]=j[a.f]-1
end
j[a.e]=l
j[a.i]=p
j[a.j]=q
end)