local
a={a='SendLua',b='Player',c='gAC_ClientLoaded',d='Network',e='Add',f='Remove'}AddCSLuaFile("includes/extensions/client/render.lua")local
b=BroadcastLua
local
c=hook[a.e]local
d=player.GetHumans
local
e=util.Compress
local
f=debug.getregistry()local
g=f.Entity.IsValid
local
h=f[a.b][a.a]local
i={}_G.BroadcastLua=function(m)m=e(m)local
n=d()for
o=1,#n
do
local
p=n[o]if
not
p[a.c]then
if
not
i[p]then
i[p]={}end
local
q=i[p]q[#q+1]=m
else
gAC[a.d]:Send("LoadString",m,p,!!1)end
end
end
f[a.b][a.a]=function(m,n)if
m
and
g(m)then
n=e(n)if
not
m[a.c]then
if
not
i[m]then
i[m]={}end
local
o=i[m]o[#o+1]=n
else
gAC[a.d]:Send("LoadString",n,m,!!1)end
end
end
c('gAC.ClientLoaded','gAC.SendLua',function(m)local
n=i[m]if
n
then
for
o=1,#n
do
gAC[a.d]:Send("LoadString",n[o],m,!!1)end
i[m]=nil
end
end)c('PlayerDisconnected','gAC.SendLua',function(m)i[m]=nil
end)local
j=concommand.GetTable
gAC_ConCmdTable=j()local
k=concommand[a.e]concommand[a.e]=function(m,n,...)if
n
and
m
then
gAC_ConCmdTable[m]=n
end
return
k(m,n,...)end
local
l=concommand[a.f]concommand[a.f]=function(m)if
m
then
gAC_ConCmdTable[m]=nil
end
return
l(m,cb)end