local
a={a='config',b='ALLOWCSLUA_CHECKS',c='SVCHEATS_CHECKS',d='GAC_Cvar_Checks',e='HasReceivedVarManipResults',f='AddDetection',g='CVARMANIP_PUNISHMENT',h='GAC_Cvar',i='Network',j='ConsoleCommand'}local
b=CurTime
local
c=GetConVar
local
d=hook.Add
local
e=player.GetAll
local
f=util.JSONToTable
gAC[a.i]:AddReceiver("G-ACcVarManipSV1",function(g,h)g=f(g)if((g[0]!=c("sv_allowcslua"):GetInt()&&gAC[a.a][a.b])||(g[1]!=GetConVar("sv_cheats"):GetInt()&&gAC[a.a][a.c]))then
gAC[a.f](h,"Anti C-var manipulation triggered [Code 100]",gAC[a.a][a.g],gAC[a.a].CVARMANIP_BANTIME)h[a.d]=nil
end
h[a.e]=!!1
end)if(gAC[a.a][a.b]==!!1||gAC[a.a][a.c]==!!1)then
d("Tick","gAC-CheckCvars",function()local
g=e()for
h=1,#g
do
local
i=g[h]if
i:IsBot()then
continue
end
if!i[a.d]then
continue
end
if
i:IsTimingOut()then
continue
end
if
i[a.e]==nil&&i[a.d]>0&&i[a.d]<=b()then
if
i[a.h]>6
then
gAC[a.f](i,"C-var manipulation results haven't returned [Code 101]",gAC[a.a][a.g],-1)i[a.d]=nil
continue
end
i[a.h]=i[a.h]+1
i[a.d]=b()+20
gAC[a.i]:Send("G-ACcVarManipCS1","",i)continue
end
if
i[a.d]>b()then
continue
end
i[a.e]=nil
i[a.h]=0
i[a.d]=b()+15
gAC[a.i]:Send("G-ACcVarManipCS1","",i)end
end)end
d("gAC.CLFilesLoaded","CheckCvars",function(g)g[a.h]=0
g[a.d]=0
end)if
gAC[a.a].DISABLE_BAD_COMMANDS
then
d("Initialize","g-ACcVarManipSV3",function()game[a.j]("sv_allowcslua 0\n")game[a.j]("sv_cheats 0\n")end)end
d("gAC.CLFilesLoaded","g-ACPlayerInitialSpawnJointimeChecker",function(g)g.JoinTimeGAC=b()end)