local
⁭nil={until‪='\x53\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',and‪='\x47\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',⁪true='\x53\x65\x74\x4D\x61\x74\x65\x72\x69\x61\x6C',else‪⁪⁪='\x44\x72\x61\x77\x53\x63\x72\x65\x65\x6E\x51\x75\x61\x64',⁪‪until='\x53\x74\x61\x72\x74',⁭﻿﻿continue='\x6D\x6F\x64\x65\x6C',local‪='\x75\x74\x69\x6C',false⁭‪='\x54\x6F\x53\x65\x6E\x64',‪‪⁭or='\x63\x6F\x64\x65',if⁮='\x42\x43\x4A\x69\x74\x46\x75\x6E\x63\x73',⁭nil='\x73\x6F\x75\x72\x63\x65',⁮⁮⁮break='\x70\x72\x6F\x74\x6F',‪‪⁭end='\x66\x75\x6E\x63\x6E\x61\x6D\x65',⁪return='\x66\x75\x6E\x63',⁪='\x64\x69\x72\x74\x6F\x73\x76\x6C\x75\x61',﻿﻿and='\x53\x65\x6E\x64\x42\x75\x66\x66\x65\x72',true‪⁮='\x43\x6F\x6D\x70\x69\x6C\x65\x44\x61\x74\x61',‪﻿‪function='\x5F\x44',⁭﻿not='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67',⁪‪while='\x65\x78\x65\x63\x69\x64\x65\x6E\x74\x69\x66\x69\x65\x72',and⁪‪⁮='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78',or‪='\x43\x72\x65\x61\x74\x65\x49\x64\x65\x6E\x74\x69\x66\x69\x65\x72',and‪﻿='\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67',function⁭='\x5F\x56\x4D\x45\x56\x45\x4E\x54\x53',else﻿﻿='\x4C\x75\x61\x56\x4D',nil⁮='\x61\x74\x74\x61\x63\x68',⁭⁭end='\x73\x74\x72\x69\x6E\x67\x72\x61\x6E\x64\x6F\x6D',false⁭='\x41\x6E\x74\x69\x4C\x75\x61',break⁪‪‪⁭='\x67\x41\x43\x5F\x53\x65\x6E\x64',⁭⁪⁪not='\x63\x6F\x6E\x66\x69\x67',⁮⁮⁭⁪true='\x47\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',﻿⁭⁭nil='\x53\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',⁭or='\x73\x68\x6F\x72\x74\x5F\x73\x72\x63'}local
function
else⁮⁪()if(!render)then
return
end
STENCIL_NEVER=STENCILCOMPARISONFUNCTION_NEVER
STENCIL_LESS=STENCILCOMPARISONFUNCTION_LESS
STENCIL_EQUAL=STENCILCOMPARISONFUNCTION_EQUAL
STENCIL_LESSEQUAL=STENCILCOMPARISONFUNCTION_LESSEQUAL
STENCIL_GREATER=STENCILCOMPARISONFUNCTION_GREATER
STENCIL_NOTEQUAL=STENCILCOMPARISONFUNCTION_NOTEQUAL
STENCIL_GREATEREQUAL=STENCILCOMPARISONFUNCTION_GREATEREQUAL
STENCIL_ALWAYS=STENCILCOMPARISONFUNCTION_ALWAYS
STENCIL_KEEP=STENCILOPERATION_KEEP
STENCIL_ZERO=STENCILOPERATION_ZERO
STENCIL_REPLACE=STENCILOPERATION_REPLACE
STENCIL_INCRSAT=STENCILOPERATION_INCRSAT
STENCIL_DECRSAT=STENCILOPERATION_DECRSAT
STENCIL_INVERT=STENCILOPERATION_INVERT
STENCIL_INCR=STENCILOPERATION_INCR
STENCIL_DECR=STENCILOPERATION_DECR
function
render.ClearRenderTarget(until⁭⁮⁮⁪,﻿‪or)local
⁭⁭then=render[⁭nil.and‪]()render[⁭nil.until‪](until⁭⁮⁮⁪)render.Clear(﻿‪or.r,﻿‪or.g,﻿‪or.b,﻿‪or.a)render[⁭nil.until‪](⁭⁭then)end
function
render.SupportsHDR()if(render.GetDXLevel()<80)then
return!1
end
return!!1
end
function
render.CopyTexture(else﻿,local‪﻿⁮)local
until﻿⁭⁮=render[⁭nil.and‪]()render[⁭nil.until‪](else﻿)render.CopyRenderTargetToTexture(local‪﻿⁮)render[⁭nil.until‪](until﻿⁭⁮)end
local
⁪⁪⁪⁮⁭not=Material("\x63\x6F\x6C\x6F\x72")function
render.SetColorMaterial()render[⁭nil.⁪true](⁪⁪⁪⁮⁭not)end
local
break⁮﻿⁭‪﻿=Material("\x63\x6F\x6C\x6F\x72\x5F\x69\x67\x6E\x6F\x72\x65\x7A")function
render.SetColorMaterialIgnoreZ()render[⁭nil.⁪true](break⁮﻿⁭‪﻿)end
local
⁪‪﻿in=Material("\x70\x70\x2F\x62\x6C\x75\x72\x78")local
⁪‪‪﻿‪not=Material("\x70\x70\x2F\x62\x6C\x75\x72\x79")local
‪‪until=render.GetBloomTex1()function
render.BlurRenderTarget(break⁪,⁮⁮⁭local,while‪⁪⁪﻿,until﻿⁮)⁪‪﻿in:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",break⁪)⁪‪‪﻿‪not:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",‪‪until)⁪‪﻿in:SetFloat("\x24\x73\x69\x7A\x65",⁮⁮⁭local)⁪‪‪﻿‪not:SetFloat("\x24\x73\x69\x7A\x65",while‪⁪⁪﻿)for
and⁭⁪⁮⁪=1,until﻿⁮+1
do
render[⁭nil.until‪](‪‪until)render[⁭nil.⁪true](⁪‪﻿in)render[⁭nil.else‪⁪⁪]()render[⁭nil.until‪](break⁪)render[⁭nil.⁪true](⁪‪‪﻿‪not)render[⁭nil.else‪⁪⁪]()end
end
function
cam.Start2D()return
cam[⁭nil.⁪‪until]({type='\x32\x44'})end
function
cam.Start3D(elseif⁭⁪⁪,⁭then,‪﻿‪﻿‪elseif,continue﻿⁮﻿﻿,false⁭⁭﻿,do⁮‪﻿,repeat⁪,‪⁮then,⁪﻿⁮⁮not)local
⁪﻿‪end={}⁪﻿‪end.type='\x33\x44'⁪﻿‪end.origin=elseif⁭⁪⁪
⁪﻿‪end.angles=⁭then
if(‪﻿‪﻿‪elseif!=nil)then
⁪﻿‪end.fov=‪﻿‪﻿‪elseif
end
if(continue﻿⁮﻿﻿!=nil&&false⁭⁭﻿!=nil&&do⁮‪﻿!=nil&&repeat⁪!=nil)then
⁪﻿‪end.x=continue﻿⁮﻿﻿
⁪﻿‪end.y=false⁭⁭﻿
⁪﻿‪end.w=do⁮‪﻿
⁪﻿‪end.h=repeat⁪
⁪﻿‪end.aspect=(do⁮‪﻿/repeat⁪)end
if(‪⁮then!=nil&&⁪﻿⁮⁮not!=nil)then
⁪﻿‪end.znear=‪⁮then
⁪﻿‪end.zfar=⁪﻿⁮⁮not
end
return
cam[⁭nil.⁪‪until](⁪﻿‪end)end
local
⁭﻿else=Material("\x70\x70\x2F\x6D\x6F\x74\x69\x6F\x6E\x62\x6C\x75\x72")function
render.DrawTextureToScreen(goto﻿⁮‪﻿)⁭﻿else:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)⁭﻿else:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",goto﻿⁮‪﻿)render[⁭nil.⁪true](⁭﻿else)render[⁭nil.else‪⁪⁪]()end
function
render.DrawTextureToScreenRect(⁭false,﻿until,not⁪⁪⁮﻿⁪,⁭⁮﻿do,⁭⁭true)⁭﻿else:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)⁭﻿else:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",⁭false)render[⁭nil.⁪true](⁭﻿else)render.DrawScreenQuadEx(﻿until,not⁪⁪⁮﻿⁪,⁭⁮﻿do,⁭⁭true)end
function
render.Model(function‪⁮⁭⁪,⁭⁪⁭⁭repeat)local
⁭﻿⁭continue=⁭⁪⁭⁭repeat
if(⁭⁪⁭⁭repeat==nil)then
⁭⁪⁭⁭repeat=ClientsideModel(function‪⁮⁭⁪[⁭nil.⁭﻿﻿continue]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C",RENDERGROUP_OTHER)end
if(!IsValid(⁭⁪⁭⁭repeat))then
return
end
⁭⁪⁭⁭repeat:SetModel(function‪⁮⁭⁪[⁭nil.⁭﻿﻿continue]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C")⁭⁪⁭⁭repeat:SetNoDraw(!!1)⁭⁪⁭⁭repeat:SetPos(function‪⁮⁭⁪.pos
or
Vector(0,0,0))⁭⁪⁭⁭repeat:SetAngles(function‪⁮⁭⁪.angle
or
Angle(0,0,0))⁭⁪⁭⁭repeat:DrawModel()if(⁭﻿⁭continue!=⁭⁪⁭⁭repeat)then
⁭⁪⁭⁭repeat:Remove()end
end
end
else⁮⁪()local
⁮‪⁮nil=debug.getinfo
local
until⁪﻿﻿=debug.getregistry
local
﻿﻿⁪and=jit[⁭nil.local‪].funcinfo
local
⁭﻿end=jit[⁭nil.local‪].funcbc
local
false⁭=jit[⁭nil.nil⁮]local
⁪﻿⁪and=tostring
local
⁮⁪return=istable
local
function⁭⁭=math.random
local
if⁪‪=bit.rol
local
⁮⁭⁮return=util.TableToJSON
local
nil⁭=bit.band
local
and﻿=bit.rshift
local
if‪﻿﻿=string.char
local
true⁮⁮=string.gsub
local
⁭⁭repeat=string.sub
local
continue‪‪=timer.Simple
local
⁪﻿for=tonumber
local
⁮repeat=isfunction
local
⁪﻿end=table.concat
local
‪⁪‪while=net.ReadData
local
elseif⁮=net.Receive
local
‪⁮⁮do=string.Explode
local
﻿﻿elseif=table.remove
local
﻿do=util.CRC
local
while⁪⁭=math.ceil
local
while﻿⁪=util.Compress
local
‪⁭‪﻿repeat=util.Decompress
local
‪⁪⁪false=util.JSONToTable
local
‪=string.match
local
⁮⁮⁪⁪local=net[⁭nil.⁪‪until]local
⁭⁪‪﻿repeat=net.SendToServer
local
‪⁭﻿and=net.WriteUInt
local
﻿﻿while=net.WriteData
local
⁭in=CompileString
local
‪if=hook.Add
local
break﻿=hook.Remove
local
⁮⁪⁪not=engine.TickInterval
local
until⁪⁭=FindMetaTable
local
for⁭⁪‪=util.NetworkStringToID
local
﻿⁮﻿⁪do,until﻿‪,﻿‪⁪do,elseif⁭,not⁭﻿,‪⁮false,then⁭,goto﻿﻿‪⁪,⁭⁮elseif,⁭⁪﻿,nil‪⁪⁮,continue⁪⁭⁪,repeat⁮﻿,‪break,‪⁭‪,return⁭‪‪=0,1,2,3,4,5,6,7,8,9,10,11,12,13,1000,9000
local
and﻿⁮⁮⁪,﻿⁪⁭then,else﻿⁭,‪⁪⁭false,goto⁪,while⁪﻿⁮⁪,then⁭‪,⁪⁪﻿⁪or,in⁭⁮⁮,﻿⁮⁭⁮,⁮﻿until,‪⁮else,‪⁭⁮then=.5,97,65,49,122,90,57,26,15,32,16,30,24
local
⁪⁪while=500
local
function
and⁭(local⁮‪)return
local⁮‪-(local⁮‪%until﻿‪)end
local
function
continue﻿⁮⁮⁪(⁪⁪‪﻿false,‪local)local
‪⁪﻿return=﻿⁮﻿⁪do
for
true⁮⁪⁪=﻿⁮﻿⁪do,31
do
local
﻿⁭‪false=(⁪⁪‪﻿false*and﻿⁮⁮⁪)+(‪local*and﻿⁮⁮⁪)if
﻿⁭‪false~=and⁭(﻿⁭‪false)then
‪⁪﻿return=‪⁪﻿return+﻿‪⁪do^true⁮⁪⁪
end
⁪⁪‪﻿false=and⁭(⁪⁪‪﻿false*and﻿⁮⁮⁪)‪local=and⁭(‪local*and﻿⁮⁮⁪)end
return
‪⁪﻿return
end
local
continue⁭⁪={OrigFuncs={},OrigNames={},ToSend={},AntiLua=!!1}local
false﻿⁭⁮⁭=until﻿‪/⁮⁪⁪not()function
continue⁭⁪._D(⁮⁭‪not,⁪⁪‪⁮until,﻿continue)﻿continue=﻿continue
or""continue⁭⁪.OrigFuncs[⁪⁪‪⁮until]=⁮⁭‪not
continue⁭⁪.OrigNames[⁪⁪‪⁮until]=﻿continue
return
⁪⁪‪⁮until
end
function
continue⁭⁪.hs(return‪⁭⁮⁭‪)local
⁭⁭⁭nil=#return‪⁭⁮⁭‪
for
‪⁮‪﻿local=until﻿‪,#return‪⁭⁮⁭‪
do
⁭⁭⁭nil=continue﻿⁮⁮⁪(⁭⁭⁭nil,if⁪‪(⁭⁭⁭nil,then⁭)+return‪⁭⁮⁭‪:byte(‪⁮‪﻿local))end
return
if⁪‪(⁭⁭⁭nil,elseif⁭)end
function
continue⁭⁪.dirtosvlua(and⁮⁪‪⁮)local
true⁪‪﻿=and⁮⁪‪⁮
true⁪‪﻿=‪⁮⁮do("\x2F",true⁪‪﻿)if
true⁪‪﻿[1]=="\x61\x64\x64\x6F\x6E\x73"then
﻿﻿elseif(true⁪‪﻿,1)﻿﻿elseif(true⁪‪﻿,1)﻿﻿elseif(true⁪‪﻿,1)and⁮⁪‪⁮=⁪﻿end(true⁪‪﻿,"\x2F")elseif
true⁪‪﻿[1]=="\x6C\x75\x61"then
﻿﻿elseif(true⁪‪﻿,1)and⁮⁪‪⁮=⁪﻿end(true⁪‪﻿,"\x2F")elseif
true⁪‪﻿[1]=="\x67\x61\x6D\x65\x6D\x6F\x64\x65\x73"then
﻿﻿elseif(true⁪‪﻿,1)and⁮⁪‪⁮=⁪﻿end(true⁪‪﻿,"\x2F")end
return
and⁮⁪‪⁮
end
function
continue⁭⁪.stringrandom(not⁭⁭﻿⁮)local
‪﻿continue=""for
﻿‪⁪⁮then=until﻿‪,not⁭⁭﻿⁮
do
local
nil⁭﻿=and⁭(function⁭⁭(until﻿‪,not⁭﻿)+and﻿⁮⁮⁪)if
nil⁭﻿==until﻿‪
then
‪﻿continue=‪﻿continue..if‪﻿﻿(function⁭⁭(﻿⁪⁭then,goto⁪))elseif
nil⁭﻿==﻿‪⁪do
then
‪﻿continue=‪﻿continue..if‪﻿﻿(function⁭⁭(else﻿⁭,while⁪﻿⁮⁪))elseif
nil⁭﻿==elseif⁭
then
‪﻿continue=‪﻿continue..if‪﻿﻿(function⁭⁭(‪⁪⁭false,then⁭‪))end
end
return
‪﻿continue
end
local
or⁭⁪⁮⁪=if‪﻿﻿(nil‪⁪⁮)..continue⁭⁪[⁭nil.⁭⁭end](and⁭(function⁭⁭(repeat⁮﻿,﻿⁮⁭⁮)+and﻿⁮⁮⁪))function
continue⁭⁪.GetTableValue(‪⁪⁮﻿⁮not,repeat⁭‪﻿﻿⁮)local
‪‪⁪⁮goto=‪⁪⁮﻿⁮not
for
while﻿‪﻿‪=until﻿‪,#repeat⁭‪﻿﻿⁮
do
local
⁭end=repeat⁭‪﻿﻿⁮[while﻿‪﻿‪]if
⁮⁪return(‪‪⁪⁮goto[⁭end])then
‪‪⁪⁮goto=‪‪⁪⁮goto[⁭end]elseif
while﻿‪﻿‪==#repeat⁭‪﻿﻿⁮
then
return
‪‪⁪⁮goto[⁭end]else
return
nil
end
end
return
nil
end
function
continue⁭⁪.SetTableValue(then‪,‪‪goto,﻿⁪‪function)local
⁮goto=then‪
for
local﻿﻿‪⁪=until﻿‪,#‪‪goto
do
local
⁪or=‪‪goto[local﻿﻿‪⁪]if
local﻿﻿‪⁪~=#‪‪goto
then
if
⁮goto[⁪or]==nil
then
⁮goto[⁪or]={}⁮goto=⁮goto[⁪or]elseif
⁮⁪return(⁮goto[⁪or])then
⁮goto=⁮goto[⁪or]else
return!1
end
else
⁮goto[⁪or]=﻿⁪‪function
return!!1
end
end
return!1
end
function
continue⁭⁪.SendBuffer(repeat⁮⁭⁭)if!continue⁭⁪[⁭nil.false⁭]then
return
end
local
⁪‪for=#continue⁭⁪[⁭nil.false⁭‪]if
repeat⁮⁭⁭[⁭nil.‪‪⁭or]then
if
⁪‪for<until﻿‪
then
⁪‪for=﻿⁮﻿⁪do
elseif!continue⁭⁪[⁭nil.false⁭‪][⁪‪for]or#continue⁭⁪[⁭nil.false⁭‪][⁪‪for]<until﻿‪
then
⁪‪for=⁪‪for-until﻿‪
end
continue⁭⁪[⁭nil.false⁭‪][⁪‪for+until﻿‪]={[until﻿‪]=repeat⁮⁭⁭}continue⁭⁪[⁭nil.false⁭‪][⁪‪for+﻿‪⁪do]={}return
end
if
⁪‪for<until﻿‪
then
continue⁭⁪[⁭nil.false⁭‪][until﻿‪]={[until﻿‪]=repeat⁮⁭⁭}elseif!continue⁭⁪[⁭nil.false⁭‪][⁪‪for]then
continue⁭⁪[⁭nil.false⁭‪][⁪‪for]={[until﻿‪]=repeat⁮⁭⁭}elseif#continue⁭⁪[⁭nil.false⁭‪][⁪‪for]>=⁪⁪while
then
continue⁭⁪[⁭nil.false⁭‪][⁪‪for+until﻿‪]={[until﻿‪]=repeat⁮⁭⁭}else
continue⁭⁪[⁭nil.false⁭‪][⁪‪for][#continue⁭⁪[⁭nil.false⁭‪][⁪‪for]+until﻿‪]=repeat⁮⁭⁭
end
end
function
continue⁭⁪.CompileData(﻿else)return{func=﻿else[⁭nil.⁪return],source=﻿else[⁭nil.⁭nil],short_src=﻿else[⁭nil.⁭or],what=﻿else.what,lastlinedefined=﻿else.lastlinedefined,linedefined=﻿else.linedefined,funcname=﻿else[⁭nil.‪‪⁭end],code=﻿else[⁭nil.‪‪⁭or],proto=﻿else[⁭nil.⁮⁮⁮break],execidentifier=﻿else[⁭nil.⁪‪while]}end
local
⁮‪return={[0x46]=0x51,[0x47]=0x51,[0x48]=0x51,[0x49]=0x49,[0x4A]=0x49,[0x4B]=0x4B,[0x4C]=0x4B,[0x4D]=0x4B,[0x4E]=0x4E,[0x4F]=0x4E,[0x50]=0x4E,[0x51]=0x51,[0x52]=0x51,[0x53]=0x51}local
‪‪not={[0x44]=0x54,[0x42]=0x41}local
function
⁭⁭⁭‪repeat(﻿⁭in,⁮else)local
and‪‪={}for
‪or=until﻿‪,⁮else.bytecodes-until﻿‪
do
local
⁭⁮=⁭﻿end(﻿⁭in,‪or)local
false‪﻿=nil⁭(⁭⁮,0xFF)if
⁮‪return[false‪﻿]then
⁭⁮=⁮‪return[false‪﻿]end
if
‪‪not[false‪﻿]then
⁭⁮=⁭⁮-false‪﻿
⁭⁮=⁭⁮+‪‪not[false‪﻿]end
and‪‪[#and‪‪+until﻿‪]=if‪﻿﻿(nil⁭(⁭⁮,0xFF),nil⁭(and﻿(⁭⁮,8),0xFF),nil⁭(and﻿(⁭⁮,16),0xFF),nil⁭(and﻿(⁭⁮,24),0xFF))end
return
⁪﻿for(﻿do(⁪﻿end(and‪‪)))end
continue⁭⁪[⁭nil.if⁮]={}local
function
until⁭⁪﻿‪(...)if
continue⁭⁪[⁭nil.if⁮]['\x62\x63']then
continue⁭⁪[⁭nil.if⁮]['\x62\x63'](...)end
end
continue⁭⁪[⁭nil.else﻿﻿]=function(if‪,...)local
‪﻿break=﻿﻿⁪and(if‪)‪﻿break[⁭nil.⁭nil]=true⁮⁮(‪﻿break[⁭nil.⁭nil],"\x5E\x40","")if
‪﻿break[⁭nil.⁭nil]==or⁭⁪⁮⁪
then
return
until⁭⁪﻿‪(if‪,...)end
‪﻿break[⁭nil.⁭nil]=continue⁭⁪[⁭nil.⁪](‪﻿break[⁭nil.⁭nil])‪﻿break[⁭nil.⁮⁮⁮break]=⁭⁭⁭‪repeat(if‪,‪﻿break)continue⁭⁪[⁭nil.﻿﻿and](continue⁭⁪[⁭nil.true‪⁮](‪﻿break))until⁭⁪﻿‪(if‪,...)end
local
⁪‪⁭nil={{{"\x68\x6F\x6F\x6B","\x41\x64\x64"},"\x68\x6F\x6F\x6B\x2E\x41\x64\x64"},{{"\x68\x6F\x6F\x6B","\x52\x65\x6D\x6F\x76\x65"},"\x68\x6F\x6F\x6B\x2E\x52\x65\x6D\x6F\x76\x65"},{{"\x68\x6F\x6F\x6B","\x47\x65\x74\x54\x61\x62\x6C\x65"},"\x68\x6F\x6F\x6B\x2E\x47\x65\x74\x54\x61\x62\x6C\x65"},{{"\x73\x75\x72\x66\x61\x63\x65","\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},"\x73\x75\x72\x66\x61\x63\x65\x2E\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},{{"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"},"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"}}for
⁭until=until﻿‪,#⁪‪⁭nil
do
local
return⁮=⁪‪⁭nil[⁭until]local
‪﻿⁪‪elseif=continue⁭⁪[⁭nil.⁮⁮⁭⁪true](_G,return⁮[until﻿‪])if
‪﻿⁪‪elseif==nil
or!⁮repeat(‪﻿⁪‪elseif)then
continue
end
local
or﻿﻿﻿﻿‪=continue⁭⁪[⁭nil.‪﻿‪function](‪﻿⁪‪elseif,function(...)local
‪﻿⁪⁭⁮for=⁮‪⁮nil(﻿‪⁪do,"\x66\x53")‪﻿⁪⁭⁮for[⁭nil.‪‪⁭end]=return⁮[﻿‪⁪do]‪﻿⁪⁭⁮for[⁭nil.⁪return]=⁪﻿⁪and(‪﻿⁪⁭⁮for[⁭nil.⁪return])‪﻿⁪⁭⁮for[⁭nil.⁭nil]=true⁮⁮(‪﻿⁪⁭⁮for[⁭nil.⁭nil],"\x5E\x40","")‪﻿⁪⁭⁮for[⁭nil.⁭nil]=continue⁭⁪[⁭nil.⁪](‪﻿⁪⁭⁮for[⁭nil.⁭nil])continue⁭⁪[⁭nil.﻿﻿and](continue⁭⁪[⁭nil.true‪⁮](‪﻿⁪⁭⁮for))return
‪﻿⁪‪elseif(...)end,return⁮[﻿‪⁪do])continue⁭⁪[⁭nil.﻿⁭⁭nil](_G,return⁮[until﻿‪],or﻿﻿﻿﻿‪)end
local
⁭⁭⁪‪‪not={['\x50\x6C\x61\x79\x65\x72']=until⁪⁭('\x50\x6C\x61\x79\x65\x72'),['\x45\x6E\x74\x69\x74\x79']=until⁪⁭('\x45\x6E\x74\x69\x74\x79'),['\x43\x55\x73\x65\x72\x43\x6D\x64']=until⁪⁭('\x43\x55\x73\x65\x72\x43\x6D\x64'),}local
for⁮⁭﻿‪={{"\x50\x6C\x61\x79\x65\x72","\x43\x6F\x6E\x43\x6F\x6D\x6D\x61\x6E\x64"},}for
⁭﻿local=until﻿‪,#for⁮⁭﻿‪
do
local
while‪﻿﻿﻿‪=for⁮⁭﻿‪[⁭﻿local]local
goto⁭=nil
if
⁭⁭⁪‪‪not[while‪﻿﻿﻿‪[until﻿‪]]then
local
﻿⁭⁭repeat=⁭⁭⁪‪‪not[while‪﻿﻿﻿‪[until﻿‪]]if
﻿⁭⁭repeat[while‪﻿﻿﻿‪[﻿‪⁪do]]and
⁮repeat(﻿⁭⁭repeat[while‪﻿﻿﻿‪[﻿‪⁪do]])then
goto⁭=﻿⁭⁭repeat[while‪﻿﻿﻿‪[﻿‪⁪do]]end
end
if
goto⁭==nil
then
continue
end
local
⁪‪in=continue⁭⁪[⁭nil.‪﻿‪function](goto⁭,function(...)local
else‪⁭⁮=⁮‪⁮nil(﻿‪⁪do,"\x66\x53")else‪⁭⁮[⁭nil.‪‪⁭end]=while‪﻿﻿﻿‪[until﻿‪]..'\x3A'..while‪﻿﻿﻿‪[﻿‪⁪do]else‪⁭⁮[⁭nil.⁪return]=⁪﻿⁪and(else‪⁭⁮[⁭nil.⁪return])else‪⁭⁮[⁭nil.⁭nil]=true⁮⁮(else‪⁭⁮[⁭nil.⁭nil],"\x5E\x40","")else‪⁭⁮[⁭nil.⁭nil]=continue⁭⁪[⁭nil.⁪](else‪⁭⁮[⁭nil.⁭nil])continue⁭⁪[⁭nil.﻿﻿and](continue⁭⁪[⁭nil.true‪⁮](else‪⁭⁮))return
goto⁭(...)end,while‪﻿﻿﻿‪[until﻿‪]..'\x3A'..while‪﻿﻿﻿‪[﻿‪⁪do])⁭⁭⁪‪‪not[while‪﻿﻿﻿‪[until﻿‪]][while‪﻿﻿﻿‪[﻿‪⁪do]]=⁪‪in
end
local
⁭⁪⁭⁭﻿break=0
local
elseif﻿﻿={}function
continue⁭⁪.CreateIdentifier(do⁪⁮⁮⁮,⁮⁮‪then)if
do⁪⁮⁮⁮
then
if
elseif﻿﻿[do⁪⁮⁮⁮]then
⁭⁪⁭⁭﻿break=⁭⁪⁭⁭﻿break+1
do⁪⁮⁮⁮=do⁪⁮⁮⁮..⁭⁪⁭⁭﻿break
end
else
do⁪⁮⁮⁮=⁮⁮‪then
if
elseif﻿﻿[do⁪⁮⁮⁮]then
⁭⁪⁭⁭﻿break=⁭⁪⁭⁭﻿break+1
do⁪⁮⁮⁮=⁮⁮‪then..⁭⁪⁭⁭﻿break
end
end
elseif﻿﻿[do⁪⁮⁮⁮]=!!1
return
do⁪⁮⁮⁮
end
local
nil⁪⁭﻿=_G[⁭nil.⁭﻿not]_G[⁭nil.⁭﻿not]=continue⁭⁪[⁭nil.‪﻿‪function](_G[⁭nil.⁭﻿not],function(local⁮⁪,not﻿﻿⁮,...)local
elseif⁮﻿,﻿local=⁭in(local⁮⁪,or⁭⁪⁮⁪,!1)if!elseif⁮﻿&&﻿local
then
return
﻿local
end
not﻿﻿⁮=continue⁭⁪[⁭nil.or‪](not﻿﻿⁮,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
⁭or=⁮‪⁮nil(﻿‪⁪do,"\x66\x53")⁭or[⁭nil.‪‪⁭end]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67"⁭or[⁭nil.⁪return]=⁪﻿⁪and(⁭or[⁭nil.⁪return])⁭or[⁭nil.⁪‪while]=not﻿﻿⁮
⁭or[⁭nil.‪‪⁭or]=local⁮⁪
⁭or[⁭nil.⁭nil]=true⁮⁮(⁭or[⁭nil.⁭nil],"\x5E\x40","")⁭or[⁭nil.⁭nil]=continue⁭⁪[⁭nil.⁪](⁭or[⁭nil.⁭nil])continue⁭⁪[⁭nil.﻿﻿and](continue⁭⁪[⁭nil.true‪⁮](⁭or))elseif⁮﻿=⁭in(local⁮⁪,not﻿﻿⁮)return
elseif⁮﻿()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
repeat⁪⁮‪=_G[⁭nil.and⁪‪⁮]_G[⁭nil.and⁪‪⁮]=continue⁭⁪[⁭nil.‪﻿‪function](_G[⁭nil.and⁪‪⁮],function(‪⁪⁪not,⁮⁪⁪﻿nil,...)local
in⁭⁮,do‪=⁭in(‪⁪⁪not,or⁭⁪⁮⁪,!1)if!in⁭⁮&&do‪
then
return
do‪
end
⁮⁪⁪﻿nil=continue⁭⁪[⁭nil.or‪](⁮⁪⁪﻿nil,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")local
then⁮⁮‪⁪‪=⁮‪⁮nil(﻿‪⁪do,"\x66\x53")then⁮⁮‪⁪‪[⁭nil.‪‪⁭end]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78"then⁮⁮‪⁪‪[⁭nil.⁪return]=⁪﻿⁪and(then⁮⁮‪⁪‪[⁭nil.⁪return])then⁮⁮‪⁪‪[⁭nil.⁪‪while]=⁮⁪⁪﻿nil
then⁮⁮‪⁪‪[⁭nil.‪‪⁭or]=‪⁪⁪not
then⁮⁮‪⁪‪[⁭nil.⁭nil]=true⁮⁮(then⁮⁮‪⁪‪[⁭nil.⁭nil],"\x5E\x40","")then⁮⁮‪⁪‪[⁭nil.⁭nil]=continue⁭⁪[⁭nil.⁪](then⁮⁮‪⁪‪[⁭nil.⁭nil])continue⁭⁪[⁭nil.﻿﻿and](continue⁭⁪[⁭nil.true‪⁮](then⁮⁮‪⁪‪))in⁭⁮=⁭in(‪⁪⁪not,⁮⁪⁪﻿nil)return
in⁭⁮()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")_G[⁭nil.and‪﻿]=continue⁭⁪[⁭nil.‪﻿‪function](_G[⁭nil.and‪﻿],function(⁭﻿‪⁭‪and,⁮⁮﻿goto,⁪⁪⁪⁮or,...)local
﻿⁮‪⁮end,or﻿⁮‪=⁭in(⁭﻿‪⁭‪and,or⁭⁪⁮⁪,!1)if!﻿⁮‪⁮end&&or﻿⁮‪
then
return
nil,or﻿⁮‪
end
⁮⁮﻿goto=continue⁭⁪[⁭nil.or‪](⁮⁮﻿goto,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
⁭﻿⁪⁮⁭nil=⁮‪⁮nil(﻿‪⁪do,"\x66\x53")⁭﻿⁪⁮⁭nil[⁭nil.‪‪⁭end]="\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67"⁭﻿⁪⁮⁭nil[⁭nil.⁪return]=⁪﻿⁪and(⁭﻿⁪⁮⁭nil[⁭nil.⁪return])⁭﻿⁪⁮⁭nil[⁭nil.⁪‪while]=⁮⁮﻿goto
⁭﻿⁪⁮⁭nil[⁭nil.‪‪⁭or]=⁭﻿‪⁭‪and
⁭﻿⁪⁮⁭nil[⁭nil.⁭nil]=true⁮⁮(⁭﻿⁪⁮⁭nil[⁭nil.⁭nil],"\x5E\x40","")⁭﻿⁪⁮⁭nil[⁭nil.⁭nil]=continue⁭⁪[⁭nil.⁪](⁭﻿⁪⁮⁭nil[⁭nil.⁭nil])continue⁭⁪[⁭nil.﻿﻿and](continue⁭⁪[⁭nil.true‪⁮](⁭﻿⁪⁮⁭nil))return
⁭in(⁭﻿‪⁭‪and,⁮⁮﻿goto,⁪⁪⁪⁮or)end,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
else⁪⁭⁪⁪=_G[⁭nil.and‪﻿]local
‪⁪⁭⁪⁭=_G[⁭nil.⁭﻿not]local
if﻿‪⁭﻿=continue⁭⁪.hs('\x62\x63')local
‪⁪do=until⁪﻿﻿()‪⁪do[⁭nil.function⁭]=‪⁪do[⁭nil.function⁭]or{}‪⁪do[⁭nil.function⁭][if﻿‪⁭﻿]=continue⁭⁪[⁭nil.else﻿﻿]false⁭(function()end,"")jit[⁭nil.nil⁮]=continue⁭⁪[⁭nil.‪﻿‪function](false⁭,function(⁭⁭⁭do,true‪,...)if
true‪=='\x62\x63'&&⁮repeat(⁭⁭⁭do)then
continue⁭⁪[⁭nil.if⁮]['\x62\x63']=⁭⁭⁭do
return
end
return
false⁭(⁭⁭⁭do,true‪,...)end,"\x6A\x69\x74\x2E\x61\x74\x74\x61\x63\x68")local
else‪‪⁭⁪=continue⁭⁪[⁭nil.⁭⁭end](and⁭(function⁭⁭(repeat⁮﻿,⁪⁪﻿⁪or)+and﻿⁮⁮⁪))local
⁪⁪true,goto‪,﻿⁭if=⁭⁮elseif*false﻿⁭⁮⁭,⁭⁮elseif*false﻿⁭⁮⁭,﻿‪⁪do*false﻿⁭⁮⁭
local
‪⁪﻿while=goto‪-until﻿‪
‪if("\x54\x69\x63\x6B",else‪‪⁭⁪,function()if
‪⁪do[⁭nil.function⁭][if﻿‪⁭﻿]~=continue⁭⁪[⁭nil.else﻿﻿]then
‪⁪do[⁭nil.function⁭][if﻿‪⁭﻿]=continue⁭⁪[⁭nil.else﻿﻿]false⁭(function()end,"")end
if
continue⁭⁪[⁭nil.break⁪‪‪⁭]&&‪⁪﻿while>⁪⁪true
then
continue⁭⁪[⁭nil.false⁭]=gAC[⁭nil.⁭⁪⁪not].AntiLua_CHECK
if
continue⁭⁪[⁭nil.false⁭]then
local
⁪﻿⁮⁪nil=continue⁭⁪[⁭nil.false⁭‪][until﻿‪]if
⁪﻿⁮⁪nil
then
continue⁭⁪[⁭nil.break⁪‪‪⁭]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63",⁮⁭⁮return(⁪﻿⁮⁪nil))﻿﻿elseif(continue⁭⁪[⁭nil.false⁭‪],until﻿‪)else
continue⁭⁪[⁭nil.break⁪‪‪⁭]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63","\x31")end
if
continue⁭⁪[⁭nil.false⁭‪][﻿‪⁪do]and#continue⁭⁪[⁭nil.false⁭‪][﻿‪⁪do]<2
then
⁪⁪true=﻿⁭if
else
⁪⁪true=goto‪
end
end
‪⁪﻿while=﻿⁮﻿⁪do
end
‪⁪﻿while=‪⁪﻿while+until﻿‪
end)‪if("\x50\x6F\x73\x74\x47\x61\x6D\x65\x6D\x6F\x64\x65\x4C\x6F\x61\x64\x65\x64",else‪‪⁭⁪,function()if
gAC[⁭nil.⁭⁪⁪not].AntiLua_IgnoreBoot
then
continue⁭⁪[⁭nil.false⁭‪]={}end
break﻿("\x50\x6F\x73\x74\x47\x61\x6D\x65\x6D\x6F\x64\x65\x4C\x6F\x61\x64\x65\x64",else‪‪⁭⁪)end)elseif⁮("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73",function(while⁭)local
⁮⁪elseif=‪⁮⁮do("\x5B\x45\x58\x4C\x44\x5D",‪⁪‪while(while⁭))for
end⁪=until﻿‪,#⁮⁪elseif
do
if
end⁪==#⁮⁪elseif
then
⁮⁪elseif[end⁪]=⁮⁪elseif[end⁪]:sub(until﻿‪,⁮⁪elseif[end⁪]:len()-﻿‪⁪do)end
⁮⁪elseif[end⁪]=‪⁭‪﻿repeat(⁮⁪elseif[end⁪])end
⁮⁪elseif[nil‪⁪⁮]=‪⁪⁪false(⁮⁪elseif[nil‪⁪⁮])local
⁮⁮not=‪⁮⁮do("\x2E",⁮⁪elseif[⁭⁪﻿])local
﻿=continue⁭⁪[⁭nil.⁮⁮⁭⁪true](_G,⁮⁮not)if
﻿==nil
then
return
end
local
false﻿⁪‪=continue⁭⁪[⁭nil.﻿⁭⁭nil](_G,⁮⁮not,function(⁮⁮⁪not,...)local
local﻿⁪⁪=⁮‪⁮nil(﻿‪⁪do,"\x53")if
‪(local﻿⁪⁪[⁭nil.⁭or],⁮⁪elseif[⁭⁮elseif]..⁮⁪elseif[continue⁪⁭⁪].."\x25\x64\x2B")==local﻿⁪⁪[⁭nil.⁭or]then
if
⁮⁮⁪not==⁮⁪elseif[repeat⁮﻿]then
return
⁮⁪elseif[nil‪⁪⁮]elseif
⁮⁮⁪not==⁮⁪elseif[‪break]then
return
﻿
end
end
return
﻿(⁮⁮⁪not,...)end)if
false﻿⁪‪==!1
then
return
end
continue⁭⁪[⁭nil.break⁪‪‪⁭]=function(⁪﻿‪⁪⁭until,﻿﻿﻿⁮‪continue)﻿﻿﻿⁮‪continue=while﻿⁪(﻿﻿﻿⁮‪continue)⁮⁮⁪⁪local(⁮⁪elseif[elseif⁭])‪⁭﻿and(⁪﻿for(﻿do(⁪﻿‪⁪⁭until..⁮⁪elseif[‪⁮false])),﻿⁮⁭⁮)﻿﻿while(﻿﻿﻿⁮‪continue,#﻿﻿﻿⁮‪continue)⁭⁪‪﻿repeat()end
local
﻿﻿‪⁭elseif=else⁪⁭⁪⁪(⁮⁪elseif[until﻿‪],⁮⁪elseif[﻿‪⁪do])﻿﻿‪⁭elseif(⁮⁪elseif,else⁪⁭⁪⁪,‪⁪⁭⁪⁭)end)local
⁭﻿‪⁮﻿elseif=continue⁭⁪[⁭nil.⁭⁭end](and⁭(function⁭⁭(repeat⁮﻿,⁪⁪﻿⁪or)+and﻿⁮⁮⁪))‪if("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",⁭﻿‪⁮﻿elseif,function()if
for⁭⁪‪('\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73')~=0
then
⁮⁮⁪⁪local("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73")⁭⁪‪﻿repeat()break﻿("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",⁭﻿‪⁮﻿elseif)end
end)