local
a={a='ALT_DETECTION_CHECKS',b='config',c='BAN_TYPE',d='AddDetection'}local
b=hook.Add
local
c=net.ReadInt
local
d=net.ReadString
local
e=net.Receive
local
f=net.Start
local
g=timer.Simple
local
h=util.SteamIDFrom64
local
i=(SERVER
and
net.Send
or
NULL)local
j=(SERVER
and
util.AddNetworkString
or
NULL)j("g-AC_AltCheck")j("g-AC_AltCheckResponse")j("g-AC_AltCheckResponse2")b("PlayerSpawn","gac-alt-spawn",function(k)if(!gAC[a.b][a.a])then
return
end
g(15,function()f("g-AC_AltCheck")i(k)end)end)e("g-AC_AltCheckResponse",function(k,l)if(!gAC[a.b][a.a])then
return
end
local
m=d()if((gAC[a.b][a.c]=="custom"&&GetUPDataGACSID64("IsBanned",m)==!!1)||(gAC[a.b][a.c]=="ulx"&&ULib.bans[h(m)]))then
gAC[a.d](l,"Ban evasion [Code 110]",gAC[a.b].ALT_DETECTION_PUNISHMENT,gAC[a.b].ALT_DETECTION_BANTIME)end
end)e("g-AC_AltCheckResponse2",function(k,l)if!gAC[a.b].ALT_DETECTION_NOTIFY_ALTS
then
return
end
local
m=c(8)if
m>1
then
gAC[a.d](l,"Joined using "..m.." alts.",!1,0)end
end)