local
a={a='JoinTimeGAC',b='gAC_CPPAimViewOld',c='gAC_CPPAimView',d='gAC_CPPAimbotDetections',e='gAC_CPPMX',f='gAC_CPPMY',g='p',h='y',i='gAC_AimbotDetected',j='config'}local
b=CurTime
local
c=IsValid
local
d=hook.Add
local
e=math.abs
local
f=util.TraceLine
local
g=(CLIENT
and
EyePos
or
NULL)if!gAC[a.j].ENABLE_CPPAIMBOT_CHECKS
then
return
end
local
h={["weapon_physgun"]=!!1,["gmod_tool"]=!!1,["weapon_physcannon"]=!!1}local
i
d("StartCommand","gAC_AntiCobalt.StartCommand",function(j,k)if(j:InVehicle()||j[a.i]||!j:Alive()||j:GetObserverMode()!=OBS_MODE_NONE||j:IsBot()||!c(j)||j:IsTimingOut()||j:PacketLoss()>80)then
return
end
if(j[a.a]==nil||!(b()>=j[a.a]+25)||j.PlayerFullyAuthenticated!=!!1)then
return
end
if
c(j:GetActiveWeapon())&&h[j:GetActiveWeapon():GetClass()]then
j[a.d]=0
return
end
j[a.e]=e(k:GetMouseX())j[a.f]=e(k:GetMouseY())j[a.c]=k:GetViewAngles()if
j[a.b]==nil
then
j[a.b]=j[a.c]return
end
if
j[a.d]==nil
then
j[a.d]=0
end
if
j[a.e]==0&&j[a.f]==0
then
if(j[a.c][a.g]~=j[a.b][a.g]&&j[a.c][a.h]~=j[a.b][a.h])then
i=f({start=j:EyePos(),endpos=j:EyePos()+((j[a.c]):Forward()*(4096*8)),filter=j})if
i.Entity:IsPlayer()then
if
j[a.d]>=40
then
j[a.i]=!!1
gAC.AddDetection(j,"C++ Aimbot detection triggered [Code 123]",gAC[a.j].CPPAIMBOT_PUNISHMENT,gAC[a.j].CPPAIMBOT_PUNSIHMENT_BANTIME)else
j[a.d]=j[a.d]+1
end
elseif
j[a.d]!=0
then
j[a.d]=j[a.d]-1
end
elseif
j[a.d]!=0
then
j[a.d]=0
end
elseif
j[a.d]!=0
then
j[a.d]=0
end
j[a.b]=j[a.c]end)