local
a={a='config',b='gAC_AimbotDetected',c='p',d='y',e='r',f='JoinTimeGAC',g='MoveManip_Threshold',h='AddDetection'}if
gAC[a.a].ENABLE_CITIZENHACK_CHECKS
then
gAC.Network:AddReceiver("gAC-CMV",function(r,s)if
s[a.b]then
return
end
gAC[a.h](s,"C-Movement Manipulation Detected #2 [Code 129]",gAC[a.a].CITIZENHACK_PUNISHMENT,gAC[a.a].CITIZENHACK_PUNSIHMENT_BANTIME)s[a.b]=!!1
end)end
if!gAC[a.a].ANTI_MOVEMANIP
then
return
end
local
b=CurTime
local
c=IsValid
local
d=hook.Add
local
e=math.abs
local
f=math.sqrt
local
g=math.sin
local
h=math.cos
local
i=math.tan
local
j=math.asin
local
k=math.acos
local
l=math.atan
local
m={["weapon_physgun"]=!!1,["gmod_tool"]=!!1,["weapon_physcannon"]=!!1,["gmod_camera"]=!!1}local
function
n(r)return
r-(r%1)end
local
function
o(r,s)local
t=10^(s
or
0)return
n(r*t+.5)/t
end
local
function
p(r,s)r[a.c]=o(r[a.c],s)r[a.d]=o(r[a.d],s)r[a.e]=o(r[a.e],s)return
r
end
local
q={[2500]=!!1,[5000]=!!1,[7500]=!!1}d("StartCommand","gAC.MoveManip",function(r,s)if(r:InVehicle()||r[a.b]||!r:Alive()||r:GetObserverMode()!=OBS_MODE_NONE||r:IsBot()||!c(r)||r:IsTimingOut()||r:PacketLoss()>80)then
return
end
if(r[a.f]==nil||!(b()>=r[a.f]+25)||r.PlayerFullyAuthenticated!=!!1)then
return
end
if
c(r:GetActiveWeapon())&&m[r:GetActiveWeapon():GetClass()]then
return
end
local
t=e(s:GetForwardMove())local
u=e(s:GetSideMove())if!r[a.g]then
r[a.g]=0
return
end
local
v=f((t^2)+(u^2))local
w=k(u/v)local
x=j(t/v)local
y=i(t/u)^-1
if((t==10000
and
u<10000
and
q[u]~=!!1
and
u>0
and
o(v)>10000)or(u==10000
and
t<10000
and
q[t]~=!!1
and
t>0
and
o(v)>10000)or(o(v)==10000))and
o(w/x)==1
and
o((g(y)^2)+(h(y)^2))==1
then
if
r[a.g]>5
then
r[a.b]=!!1
gAC[a.h](r,"C-Movement Manipulation Detected #1 [Code 129]",gAC[a.a].MOVEMANIP_PUNISHMENT,gAC[a.a].MOVEMANIP_BANTIME)return
else
r[a.g]=r[a.g]+1
end
elseif
r[a.g]>0
then
r[a.g]=r[a.g]-1
end
end)