local
a={a='PlayerHasUsergroupFromTable',b='config'}local
b=IsValid
local
c=pairs
function
gAC.PlayerHasAdminMessagePerm(d)return
gAC[a.a](d,gAC[a.b].ADMIN_MESSAGE_USERGROUPS)||d:IsAdmin()end
function
gAC.PlayerHasUnbanPerm(d)return
gAC[a.a](d,gAC[a.b].UNBAN_USERGROUPS)||d:IsSuperAdmin()end
function
gAC.PlayerHasUsergroupFromTable(d,e)if!b(d)and
d==NULL
then
return!!1
end
for
f,g
in
c(e)do
if(d:IsUserGroup(g))then
return!!1
end
end
return!1
end