local
a={a='Add',b='Exists',c='BAN_MESSAGE_SYNTAX',d='config',e='GetFormattedBanText',f='AdminMessage',g='time',h='RemoveBan',i='PlayerHasUnbanPerm',j='ClientMessage',k='BAN_TYPE',l='DELAYEDBANS',m='DELAYEDBANS_TIME',n='GetBanType',o='KICK_TYPE',p='GetBanSyntax',q='KICK_FUNC'}local
b=Color
local
c=RunConsoleCommand
local
d=concommand[a.a]local
e=file.CreateDir
local
f=file.Delete
local
g=file[a.b]local
h=file.IsDir
local
i=file.Write
local
j=hook[a.a]local
k=string.len
local
l=tonumber
local
m=timer[a.b]local
n=timer.Remove
local
o=timer.Create
local
p=isstring
local
q=player.GetBySteamID
function
gAC.GetBanSyntax(r)return
r
or
gAC[a.d][a.c]end
function
gAC.GetFormattedBanText(r,s)local
t=(gAC[a.d][a.c]or
code)..'\n's=l(s)if(s==-1)then
t=t.."Type: Kick"elseif(s>=0)then
if(s==0)then
t=t.."Type: Permanent Ban\n\nPlease appeal if you believe this is false"else
t=t.."Type: Temporary Ban\n\nPlease appeal if you believe this is false"end
end
return
t
end
if
gAC[a.d][a.k]=="custom"then
function
gAC.AddBan(r,s,t)t=l(t)r:SetUPDataGAC("gAC_IsBanned",!!1)r:SetUPDataGAC("gAC_BannedAtTime",os[a.g]())r:SetUPDataGAC("gAC_BanTime",t)r:SetUPDataGAC("gAC_BanDisplayReason",s)r:Kick(gAC[a.e](s,t))if
gAC[a.d][a.l]then
if
m('gAC.DelayedBan-'..ID)then
return
end
if
m('gAC.DelayedKick-'..ID)then
n('gAC.DelayedKick-'..ID)end
o('gAC.DelayedBan-'..ID,gAC[a.d][a.m],1,function()local
u=q(ID)if
u==!1
then
return
end
r:Kick(gAC[a.e](s,t))end)else
r:Kick(gAC[a.e](s,t))end
end
function
gAC.RemoveBan(r)r:SetUPDataGAC("gAC_IsBanned",!1)r:SetUPDataGAC("gAC_BannedAtTime",0)r:SetUPDataGAC("gAC_BanTime",1)r:SetUPDataGAC("gAC_BanDisplayReason","nil")end
function
gAC.UnbanCommand(r,s)if(!gAC[a.i](r))then
return
end
if(!h("g-ac","DATA"))then
e("g-ac")end
if(g("g-ac/"..s..".txt","DATA"))then
gAC[a.j](r,"That player is already due for an unban.",b(225,150,25))return
end
i("g-ac/"..s..".txt","")gAC[a.f](s,"Ban removed by "..r:Nick().."")end
function
gAC.BanCheck(r)if(g("g-ac/"..r:SteamID64()..".txt","DATA"))then
f("g-ac/"..r:SteamID64()..".txt")if(r:GetUPDataGAC("gAC_IsBanned")==!!1||r:GetUPDataGAC("gAC_IsBanned")=="true"||r:GetUPDataGAC("gAC_IsBanned")==1)then
gAC[a.h](r)gAC[a.f](r:Nick(),"Player's ban removed upon login (admin manually unbanned)",!1)return
end
end
if(r:GetUPDataGAC("gAC_IsBanned")==!!1||r:GetUPDataGAC("gAC_IsBanned")=="true"||r:GetUPDataGAC("gAC_IsBanned")==1)then
if((os[a.g]()>=(l(r:GetUPDataGAC("gAC_BannedAtTime"))+(tonumber(r:GetUPDataGAC("gAC_BanTime"))*60)))&&tonumber(r:GetUPDataGAC("gAC_BanTime"))!=0)then
gAC[a.h](r)gAC[a.f](r:Nick(),"Player's ban expired.",!1)else
r:Kick(gAC[a.e](r:GetUPDataGAC("gAC_BanDisplayReason"),r:GetUPDataGAC("gAC_BanTime")))end
end
end
j("PlayerInitialSpawn","g-ACPlayerInitialSpawnBanSys",function(r)gAC.BanCheck(r)end)d("gac-unban",function(r,s,t)if(!gAC[a.i](r))then
gAC[a.j](r,"You don't have permission to do that!",b(225,150,25))return
end
local
u=t[1]if(u==""||u==nil)then
gAC[a.j](r,"Please input a valid SteamID64.",b(225,150,25))return
end
if(k(u)!=17)then
gAC[a.j](r,"Please input a valid SteamID64.",b(225,150,25))return
end
gAC.UnbanCommand(r,u)end)else
local
r={}function
gAC.GetBanType(s,t,u)s=(p(s)and
s
or
s:SteamID())u=gAC[a.p](u)if
gAC[a.d][a.k]=="ulx"then
c("ulx","banid",s,t,(gAC[a.d][a.c]or
u))elseif
gAC[a.d][a.k]=="d3a"then
if(l(s:GetUPDataGAC("gAC_BanTime"))!=0)then
c("d3a","ban",s,t,"minutes","'"..(gAC[a.d][a.c]or
u).."'")else
c("d3a","perma",s,"'"..(gAC[a.d][a.c]or
u).."'")end
elseif
gAC[a.d][a.k]=="serverguard"then
c("serverguard_ban",s,t/60,(gAC[a.d][a.c]or
u))elseif
gAC[a.d][a.k]=="sam"then
SAM.AddBan(s,nil,t/60,(gAC[a.d][a.c]or
u))elseif
gAC[a.d][a.k]=="custom_func"then
gAC[a.d].BAN_FUNC(s,t,u)end
end
function
gAC.AddBan(s,t,u)if
gAC[a.d][a.l]then
local
v=s:SteamID()if
m('gAC.DelayedBan-'..v)and
r[v]then
if
r[v]['banTime']<u
or(r[v]['banTime']~=0
and
u==0)then
if
m('gAC.DelayedKick-'..v)then
n('gAC.DelayedKick-'..v)end
r[v]={['displayReason']=t,['banTime']=u}end
return
end
if
m('gAC.DelayedKick-'..v)then
n('gAC.DelayedKick-'..v)end
r[v]={['displayReason']=t,['banTime']=u}o('gAC.DelayedBan-'..v,gAC[a.d][a.m],1,function()if
r[v]then
gAC[a.n](v,r[v]['banTime'],r[v]['displayReason'])r[v]=nil
end
end)else
gAC[a.n](s,u,t)end
end
j('PlayerDisconnected','gAC.BanDisconnected',function(s)local
t=s:SteamID()if
r[t]then
if
m('gAC.DelayedBan-'..t)then
n('gAC.DelayedBan-'..t)end
gAC[a.n](t,r[t]['banTime'],r[t]['displayReason'])r[t]=nil
end
end)end
function
gAC.Kick(r,s)local
t=r:SteamID()if
gAC[a.d].DELAYEDKICKS
then
if
m('gAC.DelayedKick-'..t)or
m('gAC.DelayedBan-'..t)then
return
end
o('gAC.DelayedKick-'..t,gAC[a.d].DELAYEDKICKS_TIME,1,function()local
u=q(t)if
u==!1
then
return
end
if
gAC[a.d][a.o]=="default"then
u:Kick(gAC[a.e](s,-1))elseif
gAC[a.d][a.o]=="custom_func"then
gAC[a.d][a.q](u,gAC[a.p](s))end
end)else
if
gAC[a.d][a.o]=="default"then
r:Kick(gAC[a.e](s,-1))elseif
gAC[a.d][a.o]=="custom_func"then
gAC[a.d][a.q](r,gAC[a.p](s))end
end
end