local
a={a='config',b='STEAM_API_KEY',c='response',d='lender_steamid'}local
b=hook.Add
local
c=string.len
local
d=tonumber
local
e=util.JSONToTable
local
f=http.Fetch
function
gAC.FamilyShareCheck(g)if(c(gAC[a.a][a.b])<=1||!gAC[a.a].ENABLE_FAMILY_SHARE_CHECKS)then
return
end
f("http://api.steampowered.com/IPlayerService/IsPlayingSharedGame/v0001/?key="..gAC[a.a][a.b].."&format=json&steamid="..g:SteamID64().."&appid_playing=4000",function(h)if(!h)then
return
end
local
i=e(h)if(!i||!i[a.c]||!i[a.c][a.d])then
return
end
local
j=d(i[a.c][a.d])if(j==0)then
return
end
gAC.AddDetection(g,"Joined from family shared account [Code 105]",gAC[a.a].FAMILY_SHARE_PUNISHMENT,gAC[a.a].FAMILY_SHARE_BANTIME)end)end
b("PlayerInitialSpawn","g-ACFamilyShareCheckInitialSpawn",function(g)gAC.FamilyShareCheck(g)end)